//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Model.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long FileId { get; set; }
        public System.Guid FileName { get; set; }
        public int FileFolderId { get; set; }
        public string RealFileName { get; set; }
        public int FileTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long FeedId { get; set; }
        public byte[] Timestamp { get; set; }
        public long Size { get; set; }
    
        public virtual Feed Feed { get; set; }
        public virtual FileFolder FileFolder { get; set; }
        public virtual FileType FileType { get; set; }
    }
}
