//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Model.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstagramEntities : DbContext
    {
        public InstagramEntities()
            : base("name=InstagramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feed> Feeds { get; set; }
        public virtual DbSet<FeedComment> FeedComments { get; set; }
        public virtual DbSet<FeedCommentLike> FeedCommentLikes { get; set; }
        public virtual DbSet<FeedLike> FeedLikes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileFolder> FileFolders { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<UserFollow> UserFollows { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
