//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Model.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public string FromUserId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte[] Timestamp { get; set; }
        public int MessageTypeId { get; set; }
        public int MessageStatusTypeId { get; set; }
        public string ToUserId { get; set; }
    
        public virtual MessageStatusType MessageStatusType { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
